from models import db, User
user = User.query.filter_by(username='elfishhenry').first()
user.is_admin = True
db.session.commit()


# ONLY UNHASH THIS IF YOU ACTUALLY WANT TO THE BELOW ACTION.
# THIS WILL DELETE ALL ACCOUNTS STORED IN THE DATABASE, NEVER DO THIS.
# ONLY UNHASH THIS IF YOU ACTUALLY WANT TO THE BELOW ACTION.
# THIS WILL DELETE ALL ACCOUNTS STORED IN THE DATABASE, NEVER DO THIS.
# ONLY UNHASH THIS IF YOU ACTUALLY WANT TO THE BELOW ACTION.
# THIS WILL DELETE ALL ACCOUNTS STORED IN THE DATABASE, NEVER DO THIS.
# ONLY UNHASH THIS IF YOU ACTUALLY WANT TO THE BELOW ACTION.
# THIS WILL DELETE ALL ACCOUNTS STORED IN THE DATABASE, NEVER DO THIS.
# ONLY UNHASH THIS IF YOU ACTUALLY WANT TO THE BELOW ACTION.
# THIS WILL DELETE ALL ACCOUNTS STORED IN THE DATABASE, NEVER DO THIS.
#from models import db, User
#User.query.delete()
#db.session.commit() 
