[build]
  command = "pip install -r requirements.txt && make html"  # or your build command
  publish = "output"  # folder where your site gets built (e.g., 'output' for Pelican)

[functions]
  directory = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
